#!/bin/bash

###

mtime_dir='/path/to/mtime'
mtime_ver='1.0.8'

###

set -eu
set -o pipefail

script_dir=$(cd "$(dirname "$0")"; pwd)
root_dir=$(cd "${script_dir}/../.."; pwd)
output_dir="${root_dir}/mtime/${mtime_ver}"

FPP='gfortran -E -cpp'
FPP_FLAGS=

OMNI='F_Front'
OMNI_FLAGS="-M ${output_dir}"

files='
libmtime.f90
error_handling.f90
libmtime_hl.f90
'

mkdir -p "${output_dir}"
cd "${mtime_dir}/src"

for file in ${files}; do
	${FPP} ${FPP_FLAGS} ${file} | ${OMNI} ${OMNI_FLAGS} >/dev/null
done
